spring:
  config:
    import: "configserver:http://localhost:8071"
  profiles:
    active: dev
  application:
    name: puzzapp
  #datasource:
  #url: jdbc:postgresql://${ETH_0}:5432/postgres
  #    username: postgres
  #    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          google:
  #            client-id: ${GOOGLE_CLIENT_ID}
  #            client-secret: ${GOOGLE_CLIENT_SECRET}
  #            redirect-uri: http://localhost:${PORT}/login/oauth2/code/google
  #            scope: email,profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: puzzapp.assistenza@gmail.com
    #    password: ${PASSWORD_SMTP_EMAIL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com

server:
  port: ${PORT}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG
          debug: debug
      hibernate: error
  file:
    name: ./logging/application.log
